[package]
name = "moo1210/swiftlyeditor"
version = "0.0.1-wip"
registry = "http://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
react-roblox = "jsdotlua/react-roblox@17.0.2"
react-spring = "chriscerie/react-spring@2.0.0"
spring = "nightcycle/spring@1.0.0"
signal = "nightcycle/signal@1.0.2"
janitor = "howmanysmall/janitor@1.15.6"
knit = "sleitnick/knit@1.5.3"
testez = "roblox/testez@0.4.1"